### ISSUE TITLE
[Quest][Shaman] Rise, Champion id:42383

### ISSUE THREAD

**Issue by arft1kwerg** [Evolution-WoW/Bug-Report#1059]
Current behavior:
Shamans can softlock their campaign. Mylra cannot be recruited and if the player abandons the quest. Both Followers will be flagged as not recruited.

How it should work:

Should set a flag that ticks the follower, even if the quest is abandoned and retaken, the follower already recruited should be counted. Mylra should be able to be recruited.

https://www.wowhead.com/quest=42383/rise-champions
https://www.wowhead.com/quest=42198/champion-stormcaller-mylra

Proof (video or image):

![image](https://user-images.githubusercontent.com/29517963/167213451-5904a0ab-aeb7-4dfa-b47e-732af22e54d9.png)

**Comment by Ragelezz** [comment]
fixed

**Comment by arft1kwerg** [comment]
Issue isn't fully fixed. If the player recruits one of the champions (in my case I completed [Duke Hydraxis](https://www.wowhead.com/quest=42197/champion-duke-hydraxis)) and then abandons the quest 'Rise, Champion'. When picked up again, the quest doesn't reckognise Hydraxis as already recruited. Making the quest uncompletable.
