### ISSUE TITLE
Mage frost frozen orb not working

### ISSUE THREAD

**Issue by Humpi96** [Evolution-WoW/Bug-Report#262]
Current behavior: when you are on high ground or the orb passes trough higher terrain, the orb just passes trough or falls down. Also it dose no dmg at all. when it collides with enemy target it just passes trough.

How it should work: when you launch the orb it should stop on the first enemy hit, also gain 1 fingers of frost prock when it hits a target for the first time, also slowing for 50% on target. the dmg is AOE 

Proof (video or image): I added 2 ss. first is on the wall inside OGG, so you can see the orb falls down on the ground when you cast it, the second one is to show that no dmg is dealt and it also passes trough enemies like nothing is there.

## DON'T FORGET TO LABEL IT ACCORDINGLY TO THE ISSUE.
![ORB FALLS](https://user-images.githubusercontent.com/100777412/156591023-8ddfdee6-c4bb-41d9-a956-4dd604ce36af.jpg)
![pass trough 0 dmg](https://user-images.githubusercontent.com/100777412/156591082-edcfe3a1-a43f-44d8-b20d-513fd95103ef.jpg)

**Comment by Ragelezz** [comment]
fixed
for the texture issue: https://github.com/Evolution-WoW/Bug-Report/issues/8

**Comment by Humpi96** [comment]
the sepll is still not working as it should. when the orb hits a target it suposed to slow down a lot not just pass trough the enemy (it deals 2 ticks of dmg right now witch is not right).
Also it generates no fingers of frost prock.
